version: "3"
services:
 #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./nginx/default:/etc/nginx/sites-enabled/default
      - ./nginx/entrypoint.sh:/etc/entrypoint.sh
    networks:
      - app-network
#Postgres Service

  postgres:
    ports:
      - "5432:5432"
    image: "postgres:13"
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - database.env
    volumes:
      - ./data:/var/lib/postgresql/data/
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
